### ISSUE TITLE
Midi Context Error

### ISSUE THREAD

**Issue by Kaylin-NormanSlack** [nlaha/godot-midi#2]
https://github.com/nlaha/godot-midi-4.0/blob/f61646b7f6ca09e78d5801e82d45e1c84a6c7153/game/addons/godot_midi/midi_import_plugin.gd#L51

This line keeps bringing up a midi context error that impedes the importing process. There isn't a gdscript version of the MIDI.cs file.

**Comment by nlaha** [comment]
Sorry for the late response, I'm just now getting around to working on this project again. I think this might be for the C# version of godot-midi which is now deprecated. You can use this version with C# as the core content is all built in C++ with GDExtension.
