### ISSUE TITLE
[GodotMidi] No midi resource set gets printed to console every frame

### ISSUE THREAD

**Issue by louiidev** [nlaha/godot-midi#22]
After creating my initial node before assigning any midi resource, it just keeps printing to the console that no midi resource is selected, this seems like a bug? this is happening in the editor btw, makes sense if it happens when the project is running

![Screenshot 2024-05-18 110250](https://github.com/nlaha/godot-midi/assets/12892064/a5f078a9-a3ee-4c4f-8fbd-b97d76d4db12)

**Comment by nlaha** [comment]
Should be fixed now, for some reason GDExtension runs the _process function in the editor.
